# alegem (base img) imaginea pe care vrem sa o folosim
# in functie de ce vrem sa rulam in container
# in cazul acesta imaginea e nginx pentru ca vrem
# un web server cu nginx
FROM nginx

# copiem fisierul cu config pentru 
# prin care nginx va sti cum sa stabileasca rutele

COPY ./default.conf /etc/nginx/conf.d/default.conf